version: "2.1"
services: 
  web1:
    ports:
      - "8081:8080"
    build: 
      context: ./
      dockerfile: Dockerfile
    environment: 
      - MAX_WORKERS=2
      - MAX_BUFFERED_MSG=10000000
    networks: 
      - benchmark
    cpu_shares: 8
    mem_limit: 128M

  web2:
    ports:
      - "8082:8080"
    build: 
      context: ./
      dockerfile: Dockerfile
    environment: 
      - MAX_WORKERS=2
      - MAX_BUFFERED_MSG=10000000
    networks: 
      - benchmark
    cpu_shares: 8
    mem_limit: 128M

  proxy:
    build: 
      context: ./haproxy
      dockerfile: Dockerfile
    depends_on: 
      - web1
      - web2
    ports:
      - '80:80'
    networks: 
      - benchmark
    cpu_shares: 8
    mem_limit: 128M

networks:
  benchmark:
    driver: overlay