version: "3"
services: 
  benchmark-api1:
    ports:
      - "8081:8080"
    build: 
      context: ./
      dockerfile: Dockerfile
    networks: 
      - benchmark

  benchmark-api2:
    ports:
      - "8082:8080"
    build: 
      context: ./
      dockerfile: Dockerfile
    networks: 
      - benchmark

  proxy:
    build: 
      context: ./haproxy
      dockerfile: Dockerfile
    depends_on: 
      - benchmark-api1
      - benchmark-api2
    ports:
      - '80:80'
    networks: 
      - benchmark

networks:
  benchmark:
    driver: overlay